name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js '18'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y nodejs
        sudo apt-get install -y npm
        sudo ln -s /usr/bin/nodejs /usr/bin/node
        node --version
        npm --version

    - run: npm i --legacy-peer-deps
    - run: npm run test

  empacotar:

    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js '18'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y nodejs
        sudo apt-get install -y npm
        sudo ln -s /usr/bin/nodejs /usr/bin/node
        node --version
        npm --version

    - name: Install Dependencies
      run:
        npm install --legacy-peer-deps

    - name: Build TypeScript
      run: 
        npm run build 

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist
